{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "93a4f743-95a7-42d5-b79b-b75844bf4486",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded features shape: (73367, 14)\n",
      "Columns with missing values (pre-imputation):\n",
      "neighbourhood_median_price    6789\n",
      "dtype: int64\n",
      "Train shape: (62361, 13) Test shape: (11006, 13)\n",
      "Ridge MAE: 52.7678  RMSE: 87.6498\n",
      "Saved Ridge baseline to C:/Users/DELL/Downloads/project/Elevate labs/airbnb_pricing/models/model_ridge.joblib\n",
      "Training until validation scores don't improve for 50 rounds\n",
      "[100]\ttraining's rmse: 79.9628\tvalid_1's rmse: 83.7191\n",
      "[200]\ttraining's rmse: 77.5113\tvalid_1's rmse: 83.1293\n",
      "[300]\ttraining's rmse: 75.7116\tvalid_1's rmse: 82.847\n",
      "[400]\ttraining's rmse: 74.2525\tvalid_1's rmse: 82.6464\n",
      "[500]\ttraining's rmse: 72.9457\tvalid_1's rmse: 82.5993\n",
      "[600]\ttraining's rmse: 71.9124\tvalid_1's rmse: 82.5363\n",
      "[700]\ttraining's rmse: 70.887\tvalid_1's rmse: 82.4873\n",
      "Early stopping, best iteration is:\n",
      "[673]\ttraining's rmse: 71.165\tvalid_1's rmse: 82.4594\n",
      "LightGBM MAE: 46.6932  RMSE: 82.4594\n",
      "Saved LightGBM model to C:/Users/DELL/Downloads/project/Elevate labs/airbnb_pricing/models/model_lightgbm.joblib\n"
     ]
    }
   ],
   "source": [
    "# src/train_model.py\n",
    "import pandas as pd\n",
    "import os\n",
    "import joblib\n",
    "import numpy as np\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import Ridge\n",
    "from sklearn.metrics import mean_absolute_error, mean_squared_error\n",
    "from sklearn.impute import SimpleImputer\n",
    "import lightgbm as lgb\n",
    "\n",
    "# Paths (adjust if your project folder is elsewhere)\n",
    "IN = os.path.join(\"C:/Users/DELL/Downloads/project/Elevate labs/airbnb_pricing/data/airbnb_features.csv\")\n",
    "MODEL_OUT = os.path.join(\"C:/Users/DELL/Downloads/project/Elevate labs/airbnb_pricing/models/model_lightgbm.joblib\")\n",
    "BASELINE_OUT = os.path.join(\"C:/Users/DELL/Downloads/project/Elevate labs/airbnb_pricing/models/model_ridge.joblib\")\n",
    "\n",
    "def train():\n",
    "    # Load features\n",
    "    df = pd.read_csv(IN, low_memory=False)\n",
    "    print(\"Loaded features shape:\", df.shape)\n",
    "\n",
    "    # Define target and X\n",
    "    target = \"price\"\n",
    "    if target not in df.columns:\n",
    "        raise ValueError(\"Target column 'price' not found in features CSV.\")\n",
    "\n",
    "    X = df.drop(columns=[target]).copy()\n",
    "    y = df[target].values\n",
    "\n",
    "    # Convert all feature cols to numeric (non-numeric -> NaN)\n",
    "    X = X.apply(pd.to_numeric, errors='coerce')\n",
    "\n",
    "    # Show which columns have NaNs and how many (for debugging)\n",
    "    nan_counts = X.isna().sum()\n",
    "    nan_cols = nan_counts[nan_counts > 0].sort_values(ascending=False)\n",
    "    if not nan_cols.empty:\n",
    "        print(\"Columns with missing values (pre-imputation):\")\n",
    "        print(nan_cols)\n",
    "    else:\n",
    "        print(\"No missing values found in features (pre-imputation).\")\n",
    "\n",
    "    # Impute numeric NaNs with median (Ridge requires no NaNs)\n",
    "    imputer = SimpleImputer(strategy=\"median\")\n",
    "    X_imputed_arr = imputer.fit_transform(X)  # returns numpy array\n",
    "    X_imputed = pd.DataFrame(X_imputed_arr, columns=X.columns, index=X.index)\n",
    "\n",
    "    # Sanity check: any remaining NaNs?\n",
    "    if X_imputed.isna().sum().sum() > 0:\n",
    "        raise RuntimeError(\"Imputation failed — NaNs remain in X_imputed.\")\n",
    "\n",
    "    # Simple train-test split\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.15, random_state=42)\n",
    "    print(\"Train shape:\", X_train.shape, \"Test shape:\", X_test.shape)\n",
    "\n",
    "    # Baseline: Ridge regression\n",
    "    ridge = Ridge(alpha=1.0, random_state=42)\n",
    "    ridge.fit(X_train, y_train)\n",
    "    y_pred_ridge = ridge.predict(X_test)\n",
    "    ridge_mae = mean_absolute_error(y_test, y_pred_ridge)\n",
    "    ridge_rmse = np.sqrt(mean_squared_error(y_test, y_pred_ridge))\n",
    "    print(f\"Ridge MAE: {ridge_mae:.4f}  RMSE: {ridge_rmse:.4f}\")\n",
    "    os.makedirs(os.path.dirname(BASELINE_OUT), exist_ok=True)\n",
    "    joblib.dump(ridge, BASELINE_OUT)\n",
    "    print(f\"Saved Ridge baseline to {BASELINE_OUT}\")\n",
    "\n",
    "    # LightGBM dataset (LightGBM can handle NaNs but we pass imputed data for consistency)\n",
    "    lgb_train = lgb.Dataset(X_train, label=y_train)\n",
    "    lgb_val = lgb.Dataset(X_test, label=y_test, reference=lgb_train)\n",
    "\n",
    "    params = {\n",
    "        \"objective\": \"regression\",\n",
    "        \"metric\": \"rmse\",\n",
    "        \"verbosity\": -1,\n",
    "        \"boosting_type\": \"gbdt\",\n",
    "        \"learning_rate\": 0.05,\n",
    "        \"num_leaves\": 31,\n",
    "        \"seed\": 42\n",
    "    }\n",
    "\n",
    "    # Train with early stopping\n",
    "    from lightgbm import early_stopping, log_evaluation\n",
    "\n",
    "# Train with early stopping (new LightGBM API)\n",
    "    gbm = lgb.train(\n",
    "        params,\n",
    "        lgb_train,\n",
    "        num_boost_round=2000,\n",
    "        valid_sets=[lgb_train, lgb_val],\n",
    "        callbacks=[\n",
    "            early_stopping(stopping_rounds=50),\n",
    "            log_evaluation(100)\n",
    "        ]\n",
    "    )\n",
    "\n",
    "    # Evaluate\n",
    "    y_pred_gbm = gbm.predict(X_test, num_iteration=gbm.best_iteration)\n",
    "    gbm_mae = mean_absolute_error(y_test, y_pred_gbm)\n",
    "    gbm_rmse = np.sqrt(mean_squared_error(y_test, y_pred_gbm))\n",
    "    print(f\"LightGBM MAE: {gbm_mae:.4f}  RMSE: {gbm_rmse:.4f}\")\n",
    "\n",
    "    os.makedirs(os.path.dirname(MODEL_OUT), exist_ok=True)\n",
    "    joblib.dump(gbm, MODEL_OUT)\n",
    "    print(f\"Saved LightGBM model to {MODEL_OUT}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    train()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "686782c6-ca58-4d43-8dd8-ca0f74f3ff28",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "resid mean, std: -0.04373179994492364 72.97086841691015\n"
     ]
    }
   ],
   "source": [
    "import joblib, pandas as pd, numpy as np\n",
    "\n",
    "gbm = joblib.load(r\"C:\\Users\\DELL\\Downloads\\project\\Elevate labs\\airbnb_pricing\\models\\model_lightgbm.joblib\")\n",
    "ridge = joblib.load(r\"C:\\Users\\DELL\\Downloads\\project\\Elevate labs\\airbnb_pricing\\models\\model_ridge.joblib\")\n",
    "\n",
    "df = pd.read_csv(r\"C:\\Users\\DELL\\Downloads\\project\\Elevate labs\\airbnb_pricing\\data\\airbnb_features.csv\")\n",
    "X = df.drop(columns=[\"price\"]).apply(pd.to_numeric, errors=\"coerce\").fillna(df.drop(columns=[\"price\"]).median())\n",
    "y = df[\"price\"].values\n",
    "\n",
    "y_pred = gbm.predict(X, num_iteration=gbm.best_iteration)\n",
    "resid = y - y_pred\n",
    "print(\"resid mean, std:\", resid.mean(), resid.std())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9e69ff9-1cd8-4ae8-a7bc-f93586f8388e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (airbnb_env)",
   "language": "python",
   "name": "airbnb_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.23"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
